### ISSUE TITLE
iOS Spacing Bug 

### ISSUE THREAD

**Issue by Timoti** [josephfusco/angled-edges#12]
I'm getting a problem where on iOS the svg background is padded by around 15px.

I think this relates to a common svg bug with iOS, but most of the solutions seem to relate to svg image elements rather than svg backgrounds - the 1% hack, and declaring 100% width/height.

typical implementation for me is …

```
.banner-bottom-text {

	width: 100%;
	@include angled-edge(
			$location:'inside bottom',
			$hypotenuse: 'upper left',
			$fill: $col-brand-tertiary,
			$width: 1500,
			$height: 100
			);

			opacity: 0.7;	
		&::before {
			background-size: 100% 100%;
			}
}

```

Any ideas?

BTW Thanks for an amazing mixin and very much +1 on liquid dimensions please.

**Comment by josephfusco** [comment]
@Timoti can you provide a link where you are experiencing the issue? Thanks!

**Comment by Timoti** [comment]
Cheers - here at http://stanfordoffer.dontexist.com.  

The issue may not be there later if I can find ANY work around so best peek at it soon if you have a moment.  Thanks

**Comment by josephfusco** [comment]
@Timoti That is strange. Try changing your background-size to

```
background-size: cover;
```

**Comment by josephfusco** [comment]
Nevermind I see that the top angle gets cut off when that happens. 👎

**Comment by josephfusco** [comment]
I would get rid of the existing background-size properties and try again using version 2.0 which was just released. Hopefully this resolves the spacing issues you were having.

See [Upgrading from 1.x](https://github.com/josephfusco/angled-edges/blob/master/README.md#upgrading-from-1x).

Going to close this for now but feel free to open up a new issue!

**Comment by Timoti** [comment]
Yes, just got to roll this to my project -  2.0 has absolutely fixed this bug  - totally saved my bacon.  Thanks heaps Joseph for resolving so quickly
