### ISSUE TITLE
Space on the flat edge of the shape

### ISSUE THREAD

**Issue by leanda** [josephfusco/angled-edges#14]
First off, thanks for making this, it's brilliant! 

I've just hit on a small problem though when testing a site on Android. I'm getting what looks like a 1px gap on the straight edge.

I've also just had a look at your demo site on Android, just to check to make sure it wasn't something I was doing and you can see the same thing happening on the first example. The odd thing is that if I pinch and zoom in and then out again the gap disapears.

Any ideas why this might be happening?

**Comment by josephfusco** [comment]
@leanda Do you mind posting a screenshot please? Thanks!

**Comment by leanda** [comment]
@josephfusco Thanks for getting back to me so quickly. Sure, I've attached an example of the issue on the site I'm building and a screenshot of the same thing happening on your demo site.

![screenshot_2017-10-13-09-17-35](https://user-images.githubusercontent.com/2487875/31536843-0268022a-aff8-11e7-9691-f2d5c0cf1581.png)
![screenshot_2017-10-13-09-17-46](https://user-images.githubusercontent.com/2487875/31536844-0284d54e-aff8-11e7-9770-8147b390c513.png)

**Comment by josephfusco** [comment]
@leanda Thanks for posting this! I see what you mean.

Can you please provide your android version and which browser this is?

Thank you!

**Comment by leanda** [comment]
@josephfusco I've tested it on Chrome running on Android 7.1.1 and also on a really old device running Android 4.2.2 using the old default Android browser and Chrome browser version 59.

Thanks

**Comment by josephfusco** [comment]
@leanda I was able to reproduce this.

After a lot of digging into similar issues I am still not sure what could be causing it. From what I have tested so far it is definitely only android browsers as I can see the issue on my kindle too.

My suggestion right now would be to shift the shape up or down depending on if you are using "inside top", "outside top", "inside bottom", or "outside bottom".

**Comment by leanda** [comment]
@josephfusco Thanks for taking a look. Shifting the shape was my solution too, the trouble is that it creates a weird little ski jump effect where it meets. I can live with it for now, but wish I could work out what was causing it.

**Comment by josephfusco** [comment]
@leanda in regards the ski jump, maybe a negative margin of 1px on the left and right of the shape would be enough to fix it? I going to close this issue in the meantime as this is a browser issue that unfortunately is out of our control.
