### ISSUE TITLE
Transparent angles?

### ISSUE THREAD

**Issue by w3work** [josephfusco/angled-edges#16]
Hi,

is there a way to set a transparancy for the angles? If i use for example rgba(0,166,141,.8) nothing happens.

**Comment by josephfusco** [comment]
Hi @w3work,

This mixin does allow for `rgba()` to be used. Here is an example using the color you provided:

https://codepen.io/anon/pen/EGEPBp

**Comment by w3work** [comment]
Sehr geehrte Damen und Herren,

ich bin bis einschließlich 06.01.2019 nicht im Büro erreichbar. 
Ich werde Ihre Anfrage gern nach meiner Rückkehr beantworten. 
Bitte haben Sie Verständnis dafür, dass Ihre E-Mail nicht automatisch weitergeleitet wird.
In dringenden Fällen wenden Sie sich bitte an meine Kollegen im Web-Team unter web@w3work.de

-- 
Viele Grüße

Robert Sensfuß
w3work - Agentur für Online Marketing
Birkenweg 6
09569 Oederan

Telefon: +49 (0) 3 72 92 / 2882-35
Internet: https://www.w3work.de

**Comment by w3work** [comment]
Hi Joseph,
thanks for your answer and the example. It is working now! 👍
