### ISSUE TITLE
sub-pixel rounding issues with chrome zoom levels

### ISSUE THREAD

**Issue by heyprotoman** [josephfusco/angled-edges#18]
Hello - Thanks for your awesome script!  I noticed a subpixel rounding issue with chrome zoom levels (not with your code) where it looks like there is a border where the svg overlaps a div above or below the one where your svg object is attached.  This is simply fixed by adding a 1px border to the div that your svg is attached to with the same background color as the svg object. This is not an issue with your code, but I wanted to help others if they are struggling w/ this chrome issue!

**Comment by josephfusco** [comment]
@heyprotoman I think this may be similar to https://github.com/josephfusco/angled-edges/issues/14.

Thank you for your feedback and report!
