### ISSUE TITLE
Support left/right edge

### ISSUE THREAD

**Issue by mrleblanc101** [josephfusco/angled-edges#19]
Hi, 
Would it be possible to add left/right inside/outside edge support to build trapezoid shape ?
![Isosceles-Trapezoids](https://user-images.githubusercontent.com/17392251/68037812-ea73ca00-fc9e-11e9-8da6-315e16ec50f9.jpg)
![Right-Trapezoids](https://user-images.githubusercontent.com/17392251/68037813-ea73ca00-fc9e-11e9-8ba0-6793072d311b.jpg)

**Comment by josephfusco** [comment]
@mrleblanc101 I don't have any plans at this time to add that support within the mixin however you can still accomplish this utilizing this mixin with a little extra css.

https://codepen.io/fusco/pen/bGGaMeV
