### ISSUE TITLE
Docs are not up to date with API

### ISSUE THREAD

**Issue by guylyons** [josephfusco/angled-edges#20]
Recently working on a project that had this included but the mixin name as well as its params do not match up with the current documentation.

**Comment by josephfusco** [comment]
@guylyons Thanks for the feedback. Are you able to see what version of the mixin the project is using?

**Comment by guylyons** [comment]
@josephfusco My apologies, there is another package with the exact same name by a different author. Your project looks great, though. Maybe we'll switch! haha. Thanks for your quick response.
