### ISSUE TITLE
It appears the maximum width of the angled images is 1500px

### ISSUE THREAD

**Issue by chrisblakley** [josephfusco/angled-edges#4]
Tested in Chrome 49 at work, the angled image is only 1500px wide, so a hard edge is visible on one side for widescreen monitors.

![screen shot 2016-06-16 at 8 35 14 am](https://cloud.githubusercontent.com/assets/6349678/16116883/4e7cb4cc-339d-11e6-9d00-b85507f37fa4.png)

**Comment by josephfusco** [comment]
Although ugly this is intended. The mixin default width for the shape is set at 1500px.
You can set the width to a larger screen size if needed using the **width** parameter.
For example, increasing to shape to 3000px wide would be:
```scss
@include angled-edge('inside bottom','upper left',#EE3924,3000);
```
Maybe we should up the default size though and/or put a container on the demo. Thanks!
