### ISSUE TITLE
Why not clip-path ?

### ISSUE THREAD

**Issue by Swizz** [josephfusco/angled-edges#7]
I am a beginner in css, and I was hurt by curiosity when I failed in your repository.

Why do you use SVG instead of the `clip-path` property ?

I think about something like [this pen](http://codepen.io/anon/pen/ZOpgVr).

Cheers,

**Comment by josephfusco** [comment]
Hey @Swizz welcome to the marvelous world of CSS 🎉 😄 

The reason would be browser compatibility. [Clip-path is not supported in Edge or Internet Explorer](http://caniuse.com/#feat=css-clip-path)

SVG, even set as an encoded background image the way it is setup here is [supported in all major browsers even IE9!](http://caniuse.com/#feat=svg)
